version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.2-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

      - run:
          name: Database setup
          command: bundle exec rake db:migrate db:schema:load --trace

      # Run rspec in parallel
      - ruby/rubocop-check
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
